on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: >
          npx gecli deploy 
            -e MONGO_URL=$MONGO_URL 
            -e JWT_SECRET=$JWT_SECRET 
            -e TWILIO_ACCOUNT=$TWILIO_ACCOUNT 
            -e TWILIO_TOKEN=$TWILIO_TOKEN 
            -e TWILLIO_SERVICE_ID=$TWILLIO_SERVICE_ID 
            -e GRAPHQL_EDITOR_TOKEN=$GRAPHQL_EDITOR_TOKEN 
            -e SPACES_SECRET=$SPACES_SECRET 
            -e SPACES_KEY=$SPACES_KEY 
            -e SPACES_BUCKET=$SPACES_BUCKET
            -e SPACES_REGION=$SPACES_REGION
        env:
          MONGO_URL: ${{secrets.MONGO_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          TWILIO_ACCOUNT: ${{secrets.TWILIO_ACCOUNT}}
          TWILIO_TOKEN: ${{secrets.TWILIO_TOKEN}}
          TWILIO_SERVICE_ID: ${{secrets.TWILIO_SERVICE_ID}}
          GRAPHQL_EDITOR_TOKEN: ${{secrets.GRAPHQL_EDITOR_TOKEN}}
          SPACES_SECRET: ${{secrets.SPACES_SECRET}}
          SPACES_KEY: ${{secrets.SPACES_KEY}}
          SPACES_BUCKET: ${{secrets.SPACES_BUCKET}}
          SPACES_REGION: ${{secrets.SPACES_REGION}}
